apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-html-app
  template:
    metadata:
      labels:
        app: my-html-app
    spec:
      containers:
      - name: my-html-app
        image: 780714934193.dkr.ecr.eu-west-1.amazonaws.com/my-html-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-html-service
spec:
  type: LoadBalancer
  selector:
    app: my-html-app
  ports:
    - port: 80
      targetPort: 80